apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-site
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-site
  template:
    metadata:
      labels:
        app: devops-site
    spec:
      containers:
        - name: devops-site
          image: ghcr.io/sk1bid/site:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
