apiVersion: v1
kind: Service
metadata:
  name: site
  namespace: default
spec:
  type: NodePort
  selector:
    app: site
  ports:
    - name: http
      port: 8080           # порт внутри кластера
      targetPort: 8080     # порт контейнера
      nodePort: 30000      # внешний порт на ноде
