apiVersion: v1
kind: Service
metadata:
  name: devops-site
  namespace: default
spec:
  type: NodePort
  selector:
    app: devops-site
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30000
